# Generated by Django 4.2.1 on 2023-05-08 14:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_players', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('max_players', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('min_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('release_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3000)])),
                ('numberOfCopies', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('complexity', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('min_playing_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('average_playing_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_paid', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='boardgamecafe.boardgame')),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="O número deverá ter o formato: '+3512199999'", regex='^\\?1?\\d{8,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='boardgamecafe.boardgame')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='boardgamecafe.person')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='boardgamecafe.booking')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='boardgamecafe.product')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='boardgamecafe.boardgame')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='boardgamecafe.person')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='boardgamecafe.calendar'),
        ),
        migrations.AddField(
            model_name='booking',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='boardgamecafe.person'),
        ),
        migrations.AddField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='boardgamecafe.table'),
        ),
    ]
