# Generated by Django 4.2.1 on 2023-05-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgamecafe', '0002_commentlove_boardgamelove'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(default="1900-02-25"),
            preserve_default=False,
        ),
    ]
