# Generated by Django 4.2.1 on 2023-05-12 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardgamecafe', '0003_person_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='title',
            new_name='designation',
        ),
    ]
