# Generated by Django 4.2.1 on 2023-05-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardgamecafe', '0004_rename_title_title_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
    ]
