# Generated by Django 4.2.1 on 2023-05-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgamecafe', '0005_remove_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='designation',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
