# Generated by Django 4.2.1 on 2023-05-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardgamecafe', '0006_alter_person_email_alter_title_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
    ]
