# Generated by Django 4.2.1 on 2023-05-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgamecafe', '0007_remove_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='vat',
            field=models.CharField(max_length=15),
        ),
    ]
