# Generated by Django 4.2.1 on 2023-05-12 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgamecafe', '0008_alter_person_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='One of the accepted formats is +351919560372', regex='^([0]{2}[1-9]{1,3})?([\\+][0-9]{1,3})?[-\\s\\.]?[0-9]{3}[-\\s\\.]?[0-9]{3}[-\\s\\.]?[0-9]{3,6}$')]),
        ),
    ]
