# Generated by Django 4.2.1 on 2023-05-12 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardgamecafe', '0009_alter_person_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='chosen_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='boardgamecafe.title'),
        ),
    ]
